apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: trial
spec:
  containers:
    - name: mypod
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: my-vault-volume
          mountPath: "/etc/gcp"
          readOnly: true
  serviceAccountName: pod-sa
  volumes:
    - name: my-vault-volume
      persistentVolumeClaim:
        claimName: csi-pvc-gcp