apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-gcp
  namespace: trial
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: vault-gcp-storage