apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: pki-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "sys/mounts" {
      capabilities = ["read", "list"]
    }

    path "sys/mounts/*" {
      capabilities = ["create", "read", "update", "delete"]
    }

    path "pki/*" {
        capabilities = ["read","create", "list", "update", "delete"]
    }

    path "sys/leases/revoke/*" {
        capabilities = ["update"]
    }
