apiVersion: engine.kubevault.com/v1alpha1
kind: GCPAccessKeyRequest
metadata:
  name: gcp-credential2
  namespace: demo
spec:
  roleRef:
    name: gcp-key
    namespace: demo
  subjects:
  - kind: ServiceAccount
    name: sa 
    namespace: demo