apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: vault-app
  namespace: demo
spec:
  secret:
    name: vault-token
  clientConfig:
    service:
      name: vault
      scheme: HTTPS
      port: 8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1RENDQWFDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFOTVFzd0NRWURWUVFERXdKallUQWUKRncweE9UQTBNak13TkRNNE16bGFGdzB5T1RBME1qQXdORE00TXpsYU1BMHhDekFKQmdOVkJBTVRBbU5oTUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd2VBZ0xkNHpmcmEzZCs5a3RJNW1sNWZpCko4SFc5WGUwZXlyOXVLNW4walNNaXFEcWJ0QUJnNUJKUHUzYXBNSlZxRFc3TXE0WHVxcURMeFZtQzVuQXNRcjcKbEFudXdQVHEvZXJqdWREUXk3Rm5UVEFyaVQ4c0JXK28vRW55c25QUk4yNko3WkZWaUdXdk1QUTZKNnpJaGkwbwpSaUVPZysyQm1nWS9TbHNOejVETWNzb25vbHJ5eitCeE1XQjFUbmI1QjcvWVg5UXNHanN5clNITXIwOVlyMDNiCkVWclpNZnNLaUxUWDduV2ZXSTZjYWVyb0lGenpQNDRkWm9nYnc2UUMwQXFJN1pHd2MrYXJIQm9IZUMwYXZDRGkKNkZHTGpKMjlTd0kzYll3cWhDNnNSZlpXU2IxWDc5UVJQS1A0OWNXcStrbU5Vc2k5WEFtNUNnWTd3QlovVlFJRApBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFNMU03dVJxTGg2cHBiSmRFZ1JZS3JTeWxkSE00UWdrQjdRMy94ZE5ZdDEyclp4NG8KdFVjOXBDQ2VlVkYwZ01GZjViZ0VUTmU4QTFuL1ZnRGx5aUZTdEtrc0c5VHpxRmIrbzBsQTJUSi9aeTQxdnluegptOTZBWCtROUNuRnJteW1YTWc5TU1PbEtHTUFQUW41R2xpbzA0Yi9ESFczcmlsNEVVVDNNSm56TndwZ3VWRmtzCnhSL3VFY2IxZ2ZtejQxcGhUcm9CcWhselMwWmVXbzR4eElSTG5qTFN3Y0V4S1NvK0xyU2RheTdyK1ZpelA3NDUKUXB4eEF2aUtPN1BBWnlDL2FrT2Z5NkVxYm5OK1ZJa3dnNTQ3NUYvYi9YNHRqYTQwaWY5TXRNUmFPKzlWNm8vNgpoNnJEeDQ1QUdLckNvS25IMzk5R05nL2Naclh2YWR1NDRjOHRoZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K