apiVersion: authorization.kubedb.com/v1alpha1
kind: MongoDBRole
metadata:
  name: demo-role
  namespace: demo
spec:
  creationStatements:
    - "{ \"db\": \"admin\", \"roles\": [{ \"role\": \"readWrite\" }, {\"role\": \"read\", \"db\": \"foo\"}] }"
  defaultTTL: 1h
  maxTTL: 24h
  authManagerRef:
    name: vault-app
    namespace: demo
  databaseRef:
    name: mongo-app
