apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: mongo-app
  namespace: demo
spec:
  secret:
    name: mongo-user-cred # secret
  clientConfig:
    service:
      name: mongo
      scheme: mongodb
      port: 27017
    insecureSkipTLSVerify: true
---
apiVersion: v1
data:
  username: cm9vdA==
  password: cm9vdA==
kind: Secret
metadata:
  name: mongo-user-cred
  namespace: demo
