apiVersion: engine.kubevault.com/v1alpha1
kind: DatabaseAccessRequest
metadata:
  name: mdb-cred-rqst
  namespace: demo
spec:
  roleRef:
    kind: MongoDBRole
    name: mdb-role
    namespace: demo
  subjects:
    - kind: ServiceAccount
      name: demo-sa
      namespace: demo
