apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mongodb-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  mongodb:
    databaseRef:
      name: mongo-app
      namespace: demo