apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault-aws-storage
  namespace: demo
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: com.kubevault.csi.secrets
parameters:
  ref: demo/vault-app
  role: k8s.-.demo.demo-role
  engine: AWS
  path: aws