kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vault-mysql-storage
  namespace: demo
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: secrets.csi.kubevault.com
parameters:
  ref: demo/vault-app
  engine: DATABASE
  role: k8s.-.demo.demo-role
  path: database

