apiVersion: v1
kind: Secret
metadata:
  name: azure-cred
  namespace: demo
data:
  client-secret: TU1hRjdRZWVzTGZxbGRpVD***
  subscription-id: MWJmYzlmNjYtMzE2ZC0****
  client-id: MmI4NzFkNGEtNzU3ZS00YjJ******
  tenant-id: NzcyMjY4ZTUtZDk0MC00Ym*******