apiVersion: engine.kubevault.com/v1alpha1
kind: AzureAccessKeyRequest
metadata:
  name: azure-credential
  namespace: demo
spec:
  roleRef:
    name: demo-role
    namespace: demo
  subjects:
  - kind: ServiceAccount
    name: sa
    namespace: demo
