apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: vault-app
  namespace: demo
spec:
  secret:
    name: vault-token
  clientConfig:
    service:
      name: vault
      scheme: HTTPS
      port: 8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1RENDQWFDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFOTVFzd0NRWURWUVFERXdKallUQWUKRncweE9UQTFNVFV4TURFMU5EUmFGdzB5T1RBMU1USXhNREUxTkRSYU1BMHhDekFKQmdOVkJBTVRBbU5oTUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc0E0VzVBVTZaZ29nKzhISjFKcTYvV3MrCkI1VDdDMDdOeGNpbEZwdkJleEVoMnZ2ZFpmQkp3NEw3QmNkaExQYzc1OGVOMUxnaEpaSlRQRjdvRXJRbzFZM0EKaUp0YUtURHlVU1ZZSXdvOVZhSG9zWkMyWFdRTEFWZ0NOVmlVbjN3Y0pnT043cjJUVSs2dWNxY2RidUVsYWJkWgpVbzBRNHRSUDgvaWEwcElCWnV2a0ZqY2R3QUpEMzFKaGE5WGdibFBVSnROdW9pYVcvSytXWjM1TU5iK2JGQ2tRCk14Zm1aMTFNb1dsZzlUYjBRQ1ZoRzBPSWdHVy9ySU1LTHphWS85MXJSNmFFU25JRWdyUjZTczhPZ0NKVEVLUzMKaS8zd2laNVVPVlI5MVFPSkRMSkROeXJCc1lRcENGVjJ2VHcydVpoYWZUWUZ4UWZrNTlvU0w5aGpoMFZyQ1FJRApBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFyelJ1TnpUc2tpd0JPZzBFdHcrc2Y4UU00ZG01eklHS2huQ3pkVUw2Z2w3azhhUVgKUlkxM1RrME9EZnBlbEM1KzVIZTYrK1U1aUo2amFYcEIyUEZhQWtwRVJ3a0h3Qm1lOHN0b01rVHRWd1hhUVVBcwpyT1A2Y2REOVJJMlBjbFZXaG5NdVdSVnJKZStYVG1lakVjRW53cWJIT0hMTlhSYkNpNW1XNVU4a0xVc2JISmZRClB0T3RRdlYySStFNmJ4MjdaNjduQXg3QnVCWlpKbm1SQUJoc1lQQzllbFdmdlFoOVVFcVk0QWUvaTh2MEdTamcKTjRVbVNUMXFDaGQ5dG9IZVlORURMM2hDMkpORExJNWhSMy80eTBDRUcvclhsQ1ZwSmtpTlJhSm9CVmErckhNdQorM0IwZW85MGo0UUhBbVpQWTkxVmdZc09ZaGdOc2s3ZUtFdmxYZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K