apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: postgresql-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
  path: my-postgres-se
  postgres:
    databaseRef:
      name: postgres-app
      namespace: demo
    pluginName: postgresql-database-plugin
    allowedRoles:
      - "*"