apiVersion: engine.kubevault.com/v1alpha1
kind: AWSAccessKeyRequest
metadata:
  name: demo-cred
  namespace: demo
spec:
  roleRef:
    name: demo-role
    namespace: demo
  subjects:
  - kind: User
    name: nahid
    apiGroup: rbac.authorization.k8s.io
