apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: aws-role-policy
  namespace: demo
spec:
  ref:
    name: vault
    namespace: demo
  policyDocument: |
    path "sys/mounts" {
      capabilities = ["read", "list"]
    }

    path "sys/mounts/*" {
      capabilities = ["create", "read", "update", "delete"]
    }

    path "aws/config/root" {
    	capabilities = ["create", "read", "update", "delete"]
    }

    path "aws/config/lease" {
    	capabilities = ["create", "read", "update", "delete"]
    }

    path "aws/roles/*" {
    	capabilities = ["create", "update", "read", "delete"]
    }

    path "aws/creds/*" {
        capabilities = ["read"]
    }

    path "sys/leases/revoke/*" {
        capabilities = ["update"]
    }
---
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: aws-role
  namespace: demo
spec:
  roleName: "aws-role"
  policies : ["aws-role-policy"]
  serviceAccountNames: ["demo-sa"]
  serviceAccountNamespaces: ["demo"]
  ttl: "1000"
  maxTTL: "2000"
  period: "1000"
