apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: mysql-se-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "mysql-se/*" {
      capabilities = ["create", "read"]
    }