apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: psql-se-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "my-postgres-se/*" {
      capabilities = ["create", "read"]
    }