apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: psql-se-role
  namespace: demo
spec:
  vaultRef:
    name: vault
  policies:
  - ref: psql-se-policy
  subjectRef:
    kubernetes:
      serviceAccountNames:
        - "pod-sa"
      serviceAccountNamespaces:
        - "trial"
