apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-mongodb-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vault-mongodb-storage
  volumeMode: DirectoryOrCreate


