apiVersion: v1
kind: Pod
metadata:
  name: mymongodbpod
  namespace: demo
spec:
  containers:
  - name: mymongodbpod
    image: redis
    volumeMounts:
    - name: my-vault-volume
      mountPath: "/etc/foo"
      readOnly: true
  serviceAccountName: db-vault
  volumes:
    - name: my-vault-volume
      persistentVolumeClaim:
        claimName: csi-mongodb-pvc




