apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mongoData
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-claim
      containers:
      - name: mongodb-container
        image: mongo
        volumeMounts:
        - name: data-storage
          mountPath: /var/lib/mongo
        ports:
        - containerPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb-svc
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 27017