kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vault-azure-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: secrets.csi.kubevault.com
parameters:
  ref: demo/vault # namespace/AppBinding, we created this in previous step
  engine: Azure # vault engine name
  role: k8s.-.demo.azure-role # role name on vault which you want get access
  path: azure # specify the secret engine path, default is azure