apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: azure-se-policy
  namespace: demo
spec:
  vaultRef:
    name: vault
  policyDocument: |
    path "azure/*" {
      capabilities = ["create", "read"]
    }